### ISSUE TITLE
How to generate url with host ? 

### ISSUE THREAD

**Issue by sintanial** [FriendsOfSymfony/FOSJsRoutingBundle#134]
Hello, please help me with some problem.
My application divided into many services(bundles). Each service have some domains.
For example

``` yml
foo_service:
    resource: "@ServiceFooBundle/Resources/config/routing.yml"
    host: "{_host}"
    requirements:
      _host: site1.com|site2.net|site3.org
    prefix:   /

bar_service:
    resource: "@ServiceBarBundle/Resources/config/routing.yml"
    host: "{_host}"
    requirements:
      _host: example1.com|somedomain2.net|test3.org
    prefix:   /
```

Symfony2 at the present time not supported filling "host" in router. I use this decision https://github.com/symfony/symfony/pull/3965#issuecomment-27203230

That is set route params in kernel listener like this

``` php
public function onKernelRequest(GetResponseEvent $event){
     .....
     $parameters = $request->attributes->get('_route_params');
     $this->router->getContext()->setParameter('_host', $parameters['_host']);
     .....
}
```

And when i generate route in js, _host replaced by undefined. How to fix this ?
