### ISSUE TITLE
expose:true annotation and routing.yml doesnt works with FOSRestBundle

### ISSUE THREAD

**Issue by Bup3** [FriendsOfSymfony/FOSJsRoutingBundle#137]
Hello,

I have a problem with the _routing.yml_ or _@Route()_ annotation and the FOSRestBundle.

I'm using this annotation.

``` php
* @Route(options={"expose"=true})
```

and this routing.yml.

``` YAML
acme_demo_api_test:
    type: rest
    resource: Acme\DemoBundle\Controller\TestController
    name_prefix: api_
    prefix: /api
    options:
        expose: true
```

And `php app/console fos:js-routing:debug` is:

```
[router] Current routes
Name Method Scheme Host Path
```

`php app/console router:debug`

| Name | Method | Scheme | Host | Path |
| --- | --- | --- | --- | --- |
| api_test_get | GET | ANY | ANY | /api/test |
