### ISSUE TITLE
Getting redirected to "/js/routing?callback=fos.Router.setData" after logging in

### ISSUE THREAD

**Issue by ls-adrian** [FriendsOfSymfony/FOSJsRoutingBundle#140]
I'm redirecting to the `target_path` in my `success_handler` but in this case it's the above mentioned URL. This is an issue because I'd rather not be redirecting the user to a JS file.

Anyone have any ideas on how to resolve this?

**Comment by inmarelibero** [comment]
@ls-adrian how did you do exactly?

**Comment by ls-adrian** [comment]
@inmarelibero I added this to my `security.yml` file

```yml
    firewalls:
        js_router:
            pattern: ^/(js\/routing)
            security: false
```
