### ISSUE TITLE
Non standard http port on route with "host" parameter defined

### ISSUE THREAD

**Issue by chandon** [FriendsOfSymfony/FOSJsRoutingBundle#167]
When generating a route defined with the host parameter :

```
test_route:
    host: www.test.com
    path: /MyTest
    defaults: { _controller: TestBundle:Test:Test  }
```

the function Routing.generate('test_route') always generate an absolute URL using the host defined in the "host:" parameter of the route. But if the http port is not the standard port, it seems there is no way for Routing.generate to add this port to the absolute generated Url.

I tried with the parameters :

```
framework:
    router:
        http_port: 81

parameters:
    router.request_context.host: 81
```

The URL generated shoud be http://www.test.com:81/MyTest but the one generated is http://www.test.com/MyTest
