### ISSUE TITLE
Parse URL with FOSJsRoutingBundle

### ISSUE THREAD

**Issue by sunlean** [FriendsOfSymfony/FOSJsRoutingBundle#198]
Is it possible to parse a URL with FOSJSRouingBundle in JavaScript? For example, let say a route is defined like this in the `routing.yml` file:
```yml
account_signup:
    path: /signup/{account}/{period}
    defaults: { _controller: FOSUserBundle:Registration:register, account: null, period: null }
```

In JavaScript I would need to parse a raw URL:

```javascript
var url = "http://mydomain.com/signup/someone/15" // or /signup/someone/15
var result = Routing.parse(url);
```
The desired result would be:
```JSON
    {
        "name": "account_signup",
        "params": {
            "account": "someone",
            "period": 15
        }
    }
```

Or, I could explicitly pass the route name to the parse() method like this:
```javascript
var result = Routing.parse(url, 'account_signup');
```

In this case, the desired result could be:
```JSON
    {
        "account": "someone",
        "period": 15
    }
```

Could it be done?

**Comment by FredoVelcro** [comment]
Would be a great feature ! :+1:

**Comment by stof** [comment]
What is the use case to have the symfony url matcher in Javascript ?

**Comment by sunlean** [comment]
I would envision there are many use cases. I must have given the wrong case in the question. Anyway, let's say we have to create/edit reports that are related to one of the companies we have and the routes are defined as follows in the `routing.yml` file.

```YML
# routing.yml

company_create_report:
    path: /company/{company}/report/new
    defaults: { _controller: AppBundle:Report:new }

company_edit_report:
    path: /company/{company}/report/{report}/edit
    defaults: { _controller: AppBundle:Report:edit }

```
In these 2 forms, we need to fetch some data that only belongs to the specified company via Ajax. For this we define another route:

```YML
# routing.yml

company_kpis:
    path: /company/{company}/kpis
    defaults: { _controller: AppBundle:Company:getKpi }
```

Obviously we need to pass the company id to this route to get the KPIs of the company. So in the J

```JavaScript
// reportForm.js

$.get(
    Routing.generate('company_kpis', {'company': companyId})
).success(function (result) {
    // Do Something
});
```
Now we need to get the ID of the company (`companyId`) that we are currently creating/editing a report for: To be able to do this we have to pass the company info from the controller into the view like this:

```PHP
// ReportController.php

class ReportController extends Controller
{
    public function newAction(Company $company, Request $request)
    {
        // ... ...
        return $this->render('new.html.twig', [
            'company' => $company,
            // ... ...
        ];
    }
}
```

And we need to insert a small script in the template that actually creates the `companyId` JavaScript variable for the `reportForm.js`

```TWIG
<script>
var companyId = {{ company.id }};
</script>
```

I think this is the typical process. But if we have the parse functionality things will turn out. So we actually do not need to directly pass the `companyId`, which has been a tedious job.

```JavaScript
// reportForm.js

var companyId = Routing.parse(location.href).params.company;
```
, or

```JavaScript
// reportForm.js

var companyId = Routing.parse(location.href, 'company_create_report').company;
```

We could make the result as a class so that it can be used in a more friendly way:
```JavaScript
// reportForm.js

var parseResult = Routing.parse(location.href);
var routeName = parseResult.getRouteName();
var companyId = parseResult.getParam('company');
```

So far, I have explained a simple use case. I do think there will be more extensive use cases.
