### ISSUE TITLE
If "host" is set up for a route, then the port is not respected on route generation.

### ISSUE THREAD

**Issue by ZeeCoder** [FriendsOfSymfony/FOSJsRoutingBundle#204]
Suppose I have a local web server on port 8888, while my production server is on the standard 80.

Generating an absolute url with
```js
Routing.generate('news', {}, true);
```

would generate a proper absolute url, like: "http://localhost:8888/news"

By having a specific "host" in the `routing.yml` configuration however does not behave like this.

For example, having the following yml config:

```yml
news:
    resource: "@AppBundle/Controller/NewsController.php"
    type: annotation
    host: %news.domain%
```

Where "news.domain" is a parameter set to "news.example.org" on the production server and to "news.localhost" on the local machine, generating routes results in the following:

```js
Routing.generate('news');
Routing.generate('news', {}, true);

// Production results
// -> "http://news.example.org" // OK

// Local results
// -> "http://news.localhost" // Instead of the expected "http://news.localhost:8888"
```
