### ISSUE TITLE
All routes exposed

### ISSUE THREAD

**Issue by jakenoble** [FriendsOfSymfony/FOSJsRoutingBundle#218]
Is the default behaviour meant to expose all routes?

I cannot see any config that allows me to set all routes as excluded, unless I specifically go through each one. Which isn't really an options as I have a RESTFul API with lots of generated routes from the FosRestBundle.

It looks like that this bundle and the FosRestBundle do not play nice together?

**Comment by slucas-nwx** [comment]
+1

**Comment by stof** [comment]
By default, none of the routes are exposed. Please show your configuration

**Comment by jakenoble** [comment]
As requested from `config.yml`

```
fos_rest:
    routing_loader:
        default_format: html
    service:
        view_handler: app.view_handler
    view:
        mime_types: { 'csv': ['text/csv','text/plain'] }
        formats:
            html: true
            json: true
            csv: true
            xml: true
```

The following has no effect at all

```
fos_js_routing:
    routes_to_expose: [ welcome ]
```
