### ISSUE TITLE
Undefined instead of http/https

### ISSUE THREAD

**Issue by maguedon** [FriendsOfSymfony/FOSJsRoutingBundle#287]
Good afternoon !

I just updated FOSJsRoutingBundle and I noticed an issue with the protocol of the url generated. When I use `Routing.generate()`, the url contains "undefined" instead of "http". I have something like this : 
`"undefined://localhost/example.com"` instead of `"http://localhost/example.com"`.

In my browser console, there is this error  : `NS_ERROR_UNKNOWN_PROTOCOL:`.
When I replace the file "web\bundles\fosjsrouting\js\router.js" by the previous, it works.

I use the "dev-master" version and I'm in Symfony 2.8.

One route of my routing.yml :

``` yaml
app_editSeriepage:
    path:     /serie/{id}
    defaults: { _controller: AppBundle:Default:editSerie }
    options:
        expose: true
```

The js where I call it : 

``` js
    body.on('click', '#series tbody tr', function () {
        var id = $(this).attr('id');
        location.href = Routing.generate('app_editSeriepage', {id: id});
    });
```

Is there a specific configuration to add or is it a bug ?

Best regards,

Mathilde
