### ISSUE TITLE
Invalid URLs with encoded URL as a route parameter

### ISSUE THREAD

**Issue by webhdx** [FriendsOfSymfony/FOSJsRoutingBundle#322]
Looks like due to this change:
https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/master/Resources/js/router.js#L216

You are not longer able to generate proper route URL if route parameter is URL encoded string:
route:
```yaml
example_route:
    path: /lookup/{url}
    defaults:
        _controller: 'Bundle:Controller:lookup'
    requirements:
        url: .+
    options:
        expose: true
```
 example code:
```js
window.Routing.generate('example_route', {url: href});
```

it generates `http://localhost/lookup/http%3A//example.com/` instead of `http://localhost/lookup/http%3A%2F%2Fexample.com` which leads to 404 as Symfony is not able to match the route.
