### ISSUE TITLE
Requirements are actually not required for generating URL in some cases

### ISSUE THREAD

**Issue by RealJTG** [FriendsOfSymfony/FOSJsRoutingBundle#363]
Route definition

```yaml
test_route:
    path: /test/{required1}/{required2}/{optional}
    defaults:
        _controller: '\Some\Class::method'
        optional: 0
    requirements:
        optional: \d+
        required1: \d+
        required2: \d+
    methods:
        - GET
    options:
        expose: true
```

translated into this

```javascript
"test_route": {
    "tokens": [
        ["variable", "\/", "\\d+", "optional"],
        ["variable", "\/", "\\d+", "required2"],
        ["variable", "\/", "\\d+", "required1"],
        ["text", "\/test"]
    ],
    "defaults": {
        "optional": 0
    },
    "requirements": {
        "optional": "\\d+",
        "required1": "\\d+",
        "required2": "\\d+"
    },
    "hosttokens": [],
    "methods": ["GET"],
    "schemes": []
}
```

Cases:
```
Execute: Routing.generate('test_route')
Expected result: "Uncaught Error: The route "test_route" requires the parameter "required1" (or required2)
Actual result: "/test"

Execute: Routing.generate('test_route', {required1: 1})
Expected result: "Uncaught Error: The route "test_route" requires the parameter "required2"
Actual result: "/test/1"
```

Although works as expected when setting optional parameter:
```
Execute: Routing.generate('test_route', {optional: 1})
Expected result: "Uncaught Error: The route "test_route" requires the parameter "required1" (or required2)
Actual result: "Uncaught Error: The route "test_route" requires the parameter "required2"
```

--------

Setting `optional = false` by default here https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/master/Resources/public/js/router.js#L293 fixes my issue, although I haven't tested other cases yet and not quite sure what is the purpose of this variable at all.
