### ISSUE TITLE
Scheme missing in dump

### ISSUE THREAD

**Issue by takali** [FriendsOfSymfony/FOSJsRoutingBundle#370]
When I generate a JSON file of routes (`bin/console fos:js-routing:dump --format=json --target=public/js/fos_js_routes.json`), I got an issue with the scheme.

When i set a global scheme in my parameter,  the scheme is not in my json file
```
# config/services.yaml
parameters:
    router.request_context.scheme: 'https'
    asset.request_context.secure: true
```

When i force the scheme in the annotations file, for all controlles (or one specific controller)  the scheme is not in my json file
```
# config/routes/annotations.yaml
controllers:
    resource: '../src/Controller/'
    type: annotation
    defaults:
        schemes: [https]
```

If i specify the scheme in the Route annotation `@Route("/login", name="login", schemes={"https"})`, it does works and the scheme is in my json file.

The thing is i do not want to specify scheme route by route, i'd rather do it globally (in parameters.yaml or annotations.yaml) becauce it allow me to set different scheme by env (http in local, https in production...). Is there a way to set a global scheme in my dump json ?
My FOSJSRouting version is 2.4.0
Symfony version : 4.3
