### ISSUE TITLE
/js/routing?callback=fos.Router.setData working on `dev` but throws a 500 HTTP Exception on `prod` environment

### ISSUE THREAD

**Issue by DavidGarciaCat** [FriendsOfSymfony/FOSJsRoutingBundle#418]
Good day everyone,

As I was trying to explain as part of the issue's title, using this bundle works fine on my local development environment, setting the `APP_ENV` to `dev`. However, when going to production, the same route throws an internal server error.

- Being on the production server, if I switch to the `dev` environment, it loads the route;
- If I enable the Symfony profiler or if I profile that URL (with the `dev` environment set) using Blackfire, I can see the PHP memory peek does not exceed the 20 MB
- The `prod` environment causes the 500 internal server error straight away - there's no timeout delay after 30 seconds or so
- I can confirm the`vendor` was installed into the `required` block in my `composer.json` file
- I can confirm the `assets` were linked correctly, as I can browse and open the `/bundles/fosjsrouting/js/router.min.js` JS file with no errors

Does anyone have any idea about what might be happening? Any potential advice or clue to solve this problem?

Thank you, everyone, in advance,

**Comment by stof** [comment]
Check your logs to see what the error is when getting a 500 server error. Otherwise, there is no way to help you

**Comment by DavidGarciaCat** [comment]
Hey @stof 

I didn't provide them because I don't see how it might help in this specific car - still, please check the configuration files and exposed logs below:

```shell
# cat .env | grep APP_ENV

APP_ENV=prod
```

```yml
# config/packages/prod/monolog.yaml

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
```

```shell
$ tail -n 0 -f *.log
==> dev.log <==

==> nginx.access.log <==

==> nginx.error.log <==

==> prod.log <==

==> nginx.access.log <==
172.17.0.1 - development [12/Nov/2021:09:48:02 +0000] "GET /js/routing?callback=fos.Router.setData HTTP/1.0" 500 831 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
```

Any idea or suggestion?
