### ISSUE TITLE
the js script doesn't generate the same url as symfony (false extra variables)

### ISSUE THREAD

**Issue by coelhoricardo** [FriendsOfSymfony/FOSJsRoutingBundle#52]
hello,
sorry for my english

here it is my route :

``` yaml
MyBundle_indic:
    pattern: /indicateur/{affichage}/{indicateur}/{axey}/{annee}/{period}/{nbperiod}/{type}/{soustype}
    defaults: { _controller: ERDFTourBundle:Indicateur:index, affichage: 'calcul', axey: 'famille', annee : null, period : 'mois', nbperiod : 12, type : null, soustype : null }
    requirements:
        affichage: calcul|liste|image
        axey: "(famille|secteur)?"
        annee: "(\d{4})?"
        period: "(mois|trim)?"
        nbperiod: "(\d{1,2})?"
        type: "(tout|level1|level2)?"
        soustype: ".*"
    options:
        expose: true
```

Twig code :

``` twig
{{ path('MyBundle_indic', {
      'affichage': "calcul", 
      'indicateur': 'test',
      'axey': "famille",
      'nbperiod': "12" }) }}
```

generate :
/app_dev.php/indicateur/calcul/test

JS code :

``` javascript
Routing.generate('MyBundle_indic', {
      'affichage': "calcul", 
      'indicateur': 'test',
      'axey': "famille",
      'nbperiod': "12" })
```

generate:
/app_dev.php/indicateur/calcul/test?axey=famille&nbperiod=12

Thanks in advance

NB : it seems that if the script starts with variables with user value equal to the default one, those variables become extra variables (they go after the ?)
