### ISSUE TITLE
Expose generated routes by FOSRestBundle

### ISSUE THREAD

**Issue by arnestockmans** [FriendsOfSymfony/FOSJsRoutingBundle#83]
I'm using the FOSRestBundle in my application which autogenerates my routes.
I'd like to link to one of the generated routes, but I can't figure out how I should do that, if it's even possible. I tried this in my bundle's routing.yml:

``` yaml
api:
    type:     rest
    resource: Path\To\MyController
    name_prefix: api_
    options:
        expose: true
```

Am I doing something wrong, or is this a missing feature?

Edit: I just found out that if I move 'expose: true' to my app/config/routing.yml, it works. Although, I'd like to be able to limit this in my bundle's routing.yml
