### ISSUE TITLE
No routes routing JS

### ISSUE THREAD

**Issue by webberig** [FriendsOfSymfony/FOSJsRoutingBundle#85]
Hi,

I installed the bundle in a Symfony 2.2 project using the instructions:
- Added the require line to composer.json
- Ran composer update, installed assets
- Include the JS files to my page

The JS seems to work, but it doesn't contain any routes. The output of /js/routing?callback=fos.Router.setData is:

```
fos.Router.setData({"base_url":"\/app_dev.php","routes":[],"prefix":"","host":"localhost","scheme":"http"});
```

My routing file (/app/config/routing.yml) looks like this:

```
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

webberig_nessi:
    resource: "@WebberigNessiBundle/Resources/config/routing.yml"
    prefix:   /

webberig_backend:
    resource: "@WebberigBackendBundle/Resources/config/routing.yml"
    prefix:   /
```

Am I doing something wrong ?
