### ISSUE TITLE
Security parameter "requires_channel" ignored when generating https routes

### ISSUE THREAD

**Issue by nicolopignatelli** [FriendsOfSymfony/FOSJsRoutingBundle#92]
While in a secured area of my project which requires https by setting **requires_channel** parameter in security.yml **access_control** key, every call to `Routing.generate('route_name')` ignores the https requirement and generates the corresponding absolute http url.  
I managed to work around this problem by setting `schemes:  [https]` while importing my routing resource, but this is obviously not a clean solution.  
More, I encountered this issue only in my production environment; dev is just fine. I'm currently using Symfony 2.2.3.

``` yaml
security:
    access_control:
        - { path: '^/', host: secured.myproject.com, requires_channel: https }
```

``` yaml
MySecureBundle:
    resource: "@MySecureBundle/Controller/"
    type:     annotation
    host:     secured.myproject.com
    schemes:  [https]
```
